Work branch
uofu-emb/2024_lab10_Chase_Ayman pull request #1
Opened 2024-11-20 22:18 UTC by chasegriswold

Lab 10 Power branch. The README contains the recorded power draw values for the 5 different scenarios. The CICD is passing.

2024-11-21 23:22 UTC, warnerjon12 requested changes
This is a good start. See my specific comments for suggested changes.

2024-11-21 23:22 UTC, warnerjon12 commented on README.md
> +3) Run a busy loop to get 100% CPU utilization
What you have as 3), 4), and 5) are all one activity. 4) and 5) are notes suggesting how to do this. There are also 3 more scenarios (really 4 or 5 if you count using different frequencies):

1. Set up an interrupt to toggle a GPIO in response to an external signal (like in lab 5).
    1. In the main loop to invoke the wait for interrupt instruction.
    1. Drive the interrupt pin with the signal generator.
    1. Try a couple of frequencies between 1KHz and 1 MHz.
1. Run the sleep demo. https://github.com/raspberrypi/pico-playground/tree/master/sleep/hello_sleep/hello_sleep_alarm.c
    1. More details are in section 2.11.5.1 of the RP2040 datasheet.
    1. Read through the demo source and the library code to make sure that the code matches the setup description in the datasheet
    1. https://github.com/raspberrypi/pico-extras/blob/master/src/rp2_common/pico_sleep/sleep.c
1. Run the dormant demo. https://github.com/raspberrypi/pico-playground/tree/master/sleep/hello_dormant/hello_dormant_gpio.c
    1. More details are in section 2.11.5.2 of the RP2040 datasheet.

2024-11-21 23:22 UTC, warnerjon12 commented on src/hello_freertos.c
>  void blink_task(__unused void *params) {
If we really want to compare sleep_ms vs. vTaskDelay, we should run this case without the overhead of FreeRTOS

2024-11-21 23:22 UTC, warnerjon12 commented on src/hello_freertos.c
> +    // Uncomment the desired task to run ---------
Using conditional compilation with macros and using cmake's `target_compile_definitions` to create separate executables from the same source file is probably a better alternative to doing this.

2024-11-21 23:22 UTC, warnerjon12 commented on src/hello_freertos.c
> +// ----- Original Code to debug that was the first pushed to work_branch
I would move this to a debug branch to keep the work branch cleaner. In that case there is also no need to have both sections of code in either branch.

2024-11-21 23:22 UTC, warnerjon12 commented on README.md
Please include a brief description of each scenario here so it reads naturally for comparison without having to go somewhere else to interpret which is which. Please also add the power usage (I'd just multiply the current by 5 V and add it in parenthesis to what you have).

2024-12-02 18:46 UTC, chasegriswold commented
Hey Ashton, if you see this, this was the lab where my lab partner was out sick, and I followed older instructions before you updated the README with new instructions. This is the complete lab based on what we were reasonably able to accomplish, based on the original instructions.

2024-12-02 18:47 UTC, chasegriswold commented
Jon, your comments are appreciated. I spoke with Ashton about extenuating circumstances, and the lab is complete based on my reasonable ability. I had older instruction set.

2024-12-02 18:48 UTC, merged